task loader
Daniel-Slavnyi/money-manager pull request #3
Opened 2023-01-26 19:04 UTC by IvanovArtemNA

пока сделал через модуль css, потом откорректирую через style component. так же решили?

2023-01-26 19:16 UTC, Daniel-Slavnyi requested changes
Зроби будьласка стилі через Ємоушен ,я все зробив, тобі треба створити тільки Loader.styled.js

2023-01-27 01:27 UTC, IvanovArtemNA commented
обновил и начал делать навигацию.
там есть косяки но завтра в процессе исправлю

2023-01-27 08:58 UTC, Daniel-Slavnyi approved these changes

2023-01-27 09:02 UTC, Daniel-Slavnyi approved these changes

2023-01-27 09:23 UTC, merged